name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - run: go build -v -o dist/main

      - name: Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v1
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main

  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
      - uses: actions-go/update@v1
